In [62]:
import cv2
import numpy as np

chessboardSquareMM = 13
checkerboardDimension = (10, 17)

criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

object3D = np.zeros((checkerboardDimension[0] * checkerboardDimension[1], 3), np.float32)
index = 0
for i in range(checkerboardDimension[0]):
    for j in range(checkerboardDimension[1]):
        object3D[index][0] = i * chessboardSquareMM
        object3D[index][1] = j * chessboardSquareMM
        index += 1

objPoints3D = []  
imgPoints2D = [] 

checkerboards = [
    r"C:\Users\amari\Desktop\Code\Rutgers\MACHINEVISION\checkerboardphotos\IMG_7010.jpg",
    r"C:\Users\amari\Desktop\Code\Rutgers\MACHINEVISION\checkerboardphotos\IMG_7011.jpg",
    r"C:\Users\amari\Desktop\Code\Rutgers\MACHINEVISION\checkerboardphotos\IMG_7012.jpg",
    r"C:\Users\amari\Desktop\Code\Rutgers\MACHINEVISION\checkerboardphotos\IMG_7013.jpg",
    r"C:\Users\amari\Desktop\Code\Rutgers\MACHINEVISION\checkerboardphotos\IMG_7014.jpg",
    r"C:\Users\amari\Desktop\Code\Rutgers\MACHINEVISION\checkerboardphotos\IMG_7015.jpg"
]

for checkerboard in checkerboards:
    cbImage = cv2.imread(checkerboard)
    checkerboard = cv2.cvtColor(cbImage, cv2.COLOR_RGB2BGR)
    gray = cv2.cvtColor(checkerboard, cv2.COLOR_BGR2GRAY)
    ret, corners = cv2.findChessboardCorners(gray, checkerboardDimension, None)
    
    if ret:
        objPoints3D.append(object3D.copy()) 
        corners2 = cv2.cornerSubPix(gray, corners, (3, 3), (-1, -1), criteria)
        imgPoints2D.append(corners2)
        img = cv2.drawChessboardCorners(checkerboard, checkerboardDimension, corners2, ret)
        
        cv2.imshow('Chessboard Corners', checkerboard)
        cv2.waitKey(500)
        cv2.destroyAllWindows()

calibDataPath = r"C:\Users\amari\Desktop\Code\Rutgers\MACHINEVISION"

ret, cameraMatrix, distCoeff, rotationalVecs, translationVecs = cv2.calibrateCamera(objPoints3D, imgPoints2D, gray.shape[::-1], None, None)

np.savez(
    f"{calibDataPath}/CalibrationMatrix_college_cpt",
    Camera_matrix = cameraMatrix,
    distCoeff = distCoeff,
    RotationalV = rotationalVecs,
    TranslationV = translationVecs,
)


In [63]:
Calibration = np.load(f"{calib_data_path}/CalibrationMatrix_college_cpt.npz")
cameraMatrix = Calibration['Camera_matrix']
print("Camera Matrix:\n", cameraMatrix)

Camera Matrix:
 [[9.25692841e+03 0.00000000e+00 4.58239711e+02]
 [0.00000000e+00 8.37883743e+04 3.59148084e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
